stages:
- build
- docker_build
- tag

docker_build:
  image: docker.io/library/docker:stable
  except:
    refs:
    - master
  only:
    refs:
    - branches
  script:
  - echo "${docker_password}" | docker login --username=${docker_user} --password-stdin ${CI_REGISTRY}
  - docker build
    --tag "${CI_REGISTRY}/${IMAGE_FAMILY}:${CI_BUILD_REF:-dirty}"
    --target app
    ${PWD}
  - docker push "${CI_REGISTRY}/${IMAGE_FAMILY}:${CI_BUILD_REF:-dirty}"
  stage: docker_build
  variables:
    CI_REGISTRY: docker.io
    IMAGE_FAMILY: stackstate/trafficmirror-test

tag_build:
  image: docker.io/goreleaser/goreleaser:v0.124.1
  only:
    refs:
    - tags
  script:
  - goreleaser check
  - goreleaser release --rm-dist
  stage: tag
  variables:
    DOCKER_PASSWORD: ${docker_password}
    DOCKER_REGISTRY: docker.io
    DOCKER_USERNAME: ${docker_user}
    GITLAB_TOKEN: ${remco_github_api_token}
